name: 'Build and Deploy to GitHub Pages'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency: # Ensure only one workflow is running at a time
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          BUILD_PATH: /${{ github.repository }}

      - name: Upload deploy artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: build

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
